/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectopoo;
import proyectopoo.Register;

/**
 *
 * @author royerjmasache
 */
public class Sale extends javax.swing.JFrame {
    // Declaración e inicialización de variables
    String result = "";
    double total = 0;
    double sTotal = 0;
    double vat = 0;
    double value = 0;
    double totalValue = 0;
    double measure = 0;
    int deposit;
    int quantity = 0;
    /**
     * Creates new form Sale
     */
    public Sale() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        search = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblStock = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblValue = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        bill = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        lblMessage = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        lblMeasure = new javax.swing.JLabel();
        lblSubTotal = new javax.swing.JLabel();
        lblVAT = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        lblTotalValue = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText("QWERTY Store Sales System");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 11, -1, 22));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel2.setText("Insert product name:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 50, -1, -1));

        txtSearch.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        getContentPane().add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 45, 253, -1));

        search.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        getContentPane().add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(539, 47, -1, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        jLabel3.setText("Product Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 95, -1, -1));

        jLabel4.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        jLabel4.setText("Stock");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 95, -1, -1));

        jLabel5.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        jLabel5.setText("Value");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 95, -1, -1));

        lblName.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        getContentPane().add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 166, 154, 60));

        lblStock.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        getContentPane().add(lblStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 166, 120, 60));

        jLabel11.setText("$");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(423, 166, 24, 60));

        lblValue.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        getContentPane().add(lblValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(453, 166, 80, 60));

        jLabel6.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        jLabel6.setText("Measure");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(567, 95, -1, -1));

        bill.setFont(new java.awt.Font("Malayalam Sangam MN", 0, 18)); // NOI18N
        bill.setText("Bill");
        bill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                billActionPerformed(evt);
            }
        });
        getContentPane().add(bill, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 510, -1, 47));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel7.setText("Please enter the quantity of products you wish to purchase:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 240, 530, -1));

        jTextField1.setFont(new java.awt.Font("Malayalam MN", 0, 18)); // NOI18N
        jTextField1.setText("Subtotal:");
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 338, -1, -1));

        jTextField2.setFont(new java.awt.Font("Malayalam MN", 0, 18)); // NOI18N
        jTextField2.setText("VAT:");
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 407, -1, -1));

        jTextField3.setFont(new java.awt.Font("Malayalam MN", 0, 18)); // NOI18N
        jTextField3.setText("Total:");
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 480, -1, -1));

        jTextField4.setFont(new java.awt.Font("Malayalam MN", 0, 18)); // NOI18N
        jTextField4.setText("Total value:");
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 555, -1, -1));
        getContentPane().add(lblMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 338, 350, 63));

        txtQuantity.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 14)); // NOI18N
        getContentPane().add(txtQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(548, 232, 77, 41));

        lblMeasure.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        getContentPane().add(lblMeasure, new org.netbeans.lib.awtextra.AbsoluteConstraints(567, 166, 80, 60));

        lblSubTotal.setFont(new java.awt.Font("Malayalam MN", 0, 18)); // NOI18N
        getContentPane().add(lblSubTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 338, 100, 26));

        lblVAT.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        getContentPane().add(lblVAT, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 407, 100, 26));

        lblTotal.setFont(new java.awt.Font("Malayalam MN", 0, 18)); // NOI18N
        getContentPane().add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 480, 100, 26));

        lblTotalValue.setFont(new java.awt.Font("Malayalam MN", 0, 18)); // NOI18N
        getContentPane().add(lblTotalValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 555, 100, 26));

        jLabel8.setFont(new java.awt.Font("Malayalam Sangam MN", 1, 18)); // NOI18N
        jLabel8.setText("Click here to generate your invoice");
        jLabel8.setToolTipText("");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 560, -1, -1));

        jLabel9.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        jLabel9.setText("VALUES PREVIEW");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 298, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectopoo/sale.jpg"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        String nameSearch = txtSearch.getText();
        for (Product product : Register.products) {
            // Verificación del nombre a buscar que esté contenido
            if (product.getName().contains(nameSearch)){
                lblName.setText(product.getName());
                lblMeasure.setText(product.getMeasure());
                lblStock.setText(String.valueOf(product.getQuantity()));
                lblValue.setText(String.valueOf(product.getValue()));
            }
        }
    }//GEN-LAST:event_searchActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void billActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_billActionPerformed
        // TODO add your handling code here:
        // Transformación de variables
        quantity = Integer.parseInt(txtQuantity.getText());
        deposit = Integer.parseInt(lblStock.getText());
        value = Double.parseDouble(lblValue.getText());
        lblSubTotal.setText("0");
        // Estructura condicional para evaluar el valor dle producto si se encuentra en Stock
        if (quantity <= deposit){
            sTotal = quantity * value;
            deposit = deposit - quantity;
        } else {
            // Mensaje presentado cuando el Stock es insuficiente
            result = "The quantity of products in Stock is insufficient";
            lblMessage.setText(String.valueOf(result));
        }
        // Cálculo de precios a pagar
        // Cálculo del IVA
        vat = sTotal * 0.12;
        // Cálculo del precio total del producto
        total = sTotal + vat;
        // Cálculo del valor total a pagar
        totalValue = totalValue + total;
        // Uso de métodos para mostrar los resultados
        lblSubTotal.setText(String.valueOf(sTotal));
        lblVAT.setText(String.valueOf(vat));
        lblTotal.setText(String.valueOf(total));
        lblTotalValue.setText(String.valueOf(totalValue));
    }//GEN-LAST:event_billActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sale().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bill;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel lblMeasure;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblStock;
    private javax.swing.JLabel lblSubTotal;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotalValue;
    private javax.swing.JLabel lblVAT;
    private javax.swing.JLabel lblValue;
    private javax.swing.JButton search;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
